-- MySQL Script generated by MySQL Workbench
-- mar 17 nov 2020 10:58:15 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Comprin
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Comprin` ;

-- -----------------------------------------------------
-- Schema Comprin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Comprin` DEFAULT CHARACTER SET utf8 ;
USE `Comprin` ;

-- -----------------------------------------------------
-- Table `Comprin`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Comprin`.`Producto` ;

CREATE TABLE IF NOT EXISTS `Comprin`.`Producto` (
  `Id_producto` INT NOT NULL AUTO_INCREMENT,
  `NombreProducto` VARCHAR(45) NOT NULL,
  `PrecioProducto` INT NULL,
  `PuntosProducto` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Comprin`.`E-wallet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Comprin`.`E-wallet` ;

CREATE TABLE IF NOT EXISTS `Comprin`.`E-wallet` (
  `Id-wallet` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  PRIMARY KEY (`Id-wallet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Comprin`.`Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Comprin`.`Compra` ;

CREATE TABLE IF NOT EXISTS `Comprin`.`Compra` (
  `Id_Compra` INT NOT NULL,
  `FechaCompra` VARCHAR(45) NOT NULL,
  `E-wallet_Id-wallet` INT NOT NULL,
  `Producto_Id_producto` INT NOT NULL,
  PRIMARY KEY (`Id_Compra`),
  INDEX `fk_Compra_E-wallet_idx` (`E-wallet_Id-wallet` ASC),
  INDEX `fk_Compra_Producto1_idx` (`Producto_Id_producto` ASC),
  CONSTRAINT `fk_Compra_E-wallet`
    FOREIGN KEY (`E-wallet_Id-wallet`)
    REFERENCES `Comprin`.`E-wallet` (`Id-wallet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Producto1`
    FOREIGN KEY (`Producto_Id_producto`)
    REFERENCES `Comprin`.`Producto` (`Id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Comprin`.`Devolucion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Comprin`.`Devolucion` ;

CREATE TABLE IF NOT EXISTS `Comprin`.`Devolucion` (
  `Id_devolucion` INT NOT NULL AUTO_INCREMENT,
  `FechaDevolucion` VARCHAR(45) NOT NULL,
  `E-wallet_Id-wallet` INT NOT NULL,
  `Producto_Id_producto` INT NOT NULL,
  PRIMARY KEY (`Id_devolucion`),
  INDEX `fk_Devolucion_E-wallet1_idx` (`E-wallet_Id-wallet` ASC),
  UNIQUE INDEX `E-wallet_Id-wallet_UNIQUE` (`E-wallet_Id-wallet` ASC),
  INDEX `fk_Devolucion_Producto1_idx` (`Producto_Id_producto` ASC),
  UNIQUE INDEX `Producto_Id_producto_UNIQUE` (`Producto_Id_producto` ASC),
  CONSTRAINT `fk_Devolucion_E-wallet1`
    FOREIGN KEY (`E-wallet_Id-wallet`)
    REFERENCES `Comprin`.`E-wallet` (`Id-wallet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Devolucion_Producto1`
    FOREIGN KEY (`Producto_Id_producto`)
    REFERENCES `Comprin`.`Producto` (`Id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
