-- MySQL Script generated by MySQL Workbench
-- mar 17 nov 2020 14:09:09 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myplaylist
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `myplaylist` ;

-- -----------------------------------------------------
-- Schema myplaylist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myplaylist` DEFAULT CHARACTER SET utf8 ;
USE `myplaylist` ;

-- -----------------------------------------------------
-- Table `myplaylist`.`song`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myplaylist`.`song` ;

CREATE TABLE IF NOT EXISTS `myplaylist`.`song` (
  `Id_song` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Artist` VARCHAR(45) NOT NULL,
  `Album` VARCHAR(45) NULL,
  `Genre` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_song`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
